let a = 40;
let b = 20;
console.log("arthematic operator");
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(" assignment operator");
let c = 10;
c += 30;
console.log(c);
c -= 20;
console.log(c);
c *= 5;
console.log(c);
c /= 2;
console.log(c);
c %= 3;
console.log(c);
console.log("comparison operator");
let d = 10;
let e = 20;
console.log(d == e);
console.log(d != e);
console.log(d > e);
console.log(d < e);
console.log(d >= e);
console.log(d <= e);
console.log("logical operator");
let f = true;
let g = false;
console.log(f && g);
console.log(f || g);
console.log(!f);
console.log("increment/ decrement operator");
let h = 10;
h++;
console.log(h);
h--;
console.log(h);
--h;
console.log(h);
++h;
console.log(h);
console.log("And operator")
let s = 10;
let t = 20;
let u = 30;
let v = 40;

console.log(s > t && u > v);
console.log(s<t && u<v);
console.log(t>u && s<v);

console.log("Or operator")
let x = 10;
let y = 20;
let z = 30;
let w = 40;
console.log(x>y || z>w);
console.log(x<y || z<w);
console.log(y>z || x<w);
console.log("operator precedence");
let p = 10;
let q = 20;
let r = 30;
let m = 40;
console.log(p + q * r / m);
console.log(p + (q * r) / m);
console.log((p + q) * r / m);
